asp.net-core-CA-master/ASP_CA/ASP_CA/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP_CA.Models;

namespace ASP_CA.Controllers
{
    public class LoginController : Controller
    {
        private readonly User user;
        private readonly Sessions sessions;

        public LoginController(User user, Sessions sessions)
        {
            this.user = user;
            this.sessions = sessions;
        }

        public IActionResult Index()
        {
            // to highlight "Login" as the selected menu-item
            ViewData["Is_Login"] = "menu_hilite";

            return View();
        }

        public IActionResult Authenticate(string username, string password)
        {
            
            if (username != user.Username && password != user.Password )
            {
                // to highlight "Login" as the selected menu-item
                ViewData["Is_Login"] = "menu_hilite";

                ViewData["errMsg"] = "No such user or incorrect password.";
                return View("Index");
            }
            else
            {
                // use a session to track this user
                Session session = new Session()
                {
                    SessionId = Guid.NewGuid().ToString(),
                    UserId = user.UserId,
                    Timestamp = DateTimeOffset.Now.ToUnixTimeSeconds()
                };
                sessions.map[session.SessionId] = session;

                Response.Cookies.Append("sessionId", session.SessionId);
                return RedirectToAction("Index", "Gallery");
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

asp.net-core-CA-master/ASP_CA/ASP_CA/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASP_CA.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASP_CA.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Index(Sessions sessions)
        {
            
            string sessionId = HttpContext.Request.Cookies["sessionId"];
            sessions.map.Remove(sessionId);
            HttpContext.Response.Cookies.Delete("sessionId");
            return RedirectToAction("Index", "Gallery");
        }
    }
}

asp.net-core-CA-master/ASP_CA/ASP_CA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Alpha Bean Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">Alpha Bean Shop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewData["header"] == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a>
                            </li>
                        }

                    </ul>
                </div>
                <div style="float:right">
                    @if (ViewData["sessionId"] == null)
                    {
                        <a class="nav-link text-dark @ViewData["Is_Login"]" asp-controller="Login" asp-action="Index">Login</a>
                    }
                    else
                    {
                        <a class="nav-link text-dark" asp-controller="Logout" asp-action="Index">Logout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Alpha Bean Shop - <a href="mailto:alphabeanshop@gmail.com">Contact Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>